config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :posts
  resources :comments do
    post :close_thread
  end
  resources :up_votes
  resources :down_votes
  root to: 'posts#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  has_many :up_votes, as: :votable
  has_many :down_votes, as: :votable

  validates :user, :commentable, :body, presence: true

  scope :latest, -> { order(created_at: :desc) }

  def close_thread
    update(closed: true)
    comments.each { |comment| comment.close_thread }
  end

end

app/models/down_vote.rb
class DownVote < Vote

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :up_votes, as: :votable
  has_many :down_votes, as: :votable

  scope :latest, -> { order(created_at: :desc) }
end

app/models/up_vote.rb
class UpVote < Vote

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :up_votes
  has_many :down_votes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :votable, polymorphic: true

  validates :user, uniqueness: { scope: [:votable_type, :votable_id] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def create
    @comment = current_user.comments.new(comment_params)

    flash[:success] = 'Comment created' if @comment.save
    @comment.save
    respond_with @comment, location: @comment.commentable
  end

  def close_thread
    @comment = Comment.find(params[:comment_id])

    Comment.transaction do
      @comment.close_thread
    end
    redirect_to @comment
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:commentable_id, :commentable_type, :body)
  end
end

app/controllers/down_votes_controller.rb
class DownVotesController < ApplicationController
  def create
    @vote = current_user.down_votes.new(vote_params)

    if @vote.save
      flash[:success] = 'Voted'
    else
      binding.pry
      flash[:error] = 'Vote could not be saved'
    end

    redirect_to @vote.votable
  end

  private

  def vote_params
    params[:down_vote].permit(:votable_type, :votable_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.latest
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new(user_id: current_user.id)
  end

  def create
    @post = Post.new(post_params)

    if @post.save()
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    flash[:success] = 'Post updated' if @post.update_attributes(post_params)
    redirect_to post_path(@post)

  rescue ActiveRecord::StaleObjectError
    @post.reload
    render 'conflict'
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:url, :headline, :user_id, :lock_version)
  end

end

app/controllers/up_votes_controller.rb
class UpVotesController < ApplicationController
  def create
    @vote = current_user.up_votes.new(vote_params)

    if @vote.save
      flash[:success] = 'Voted'
    else
      flash[:error] = 'Vote could not be saved'
    end

    redirect_to @vote.votable
  end

  private

  def vote_params
    params[:up_vote].permit(:votable_type, :votable_id)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @vote = current_user.votes.new(vote_params)

    if @vote.save
      flash[:success] = 'Voted'
    else
      flash[:error] = 'Vote could not be saved'
    end

    redirect_to @vote.votable
  end

  private

  def vote_params
    params[:vote].permit(:votable_type, :votable_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/comments/_comment.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      
      <div class="col-md-8">
        <p><%= simple_format comment.body %></p>
      </div>
      
      <div class="col-md-4">
        <%= form_for current_user.up_votes.new(votable: comment) do |f| %>
          <%= f.hidden_field :votable_type %>
          <%= f.hidden_field :votable_id %>
          <%= f.button type: :submit, class: 'btn btn-default' do %>
            <span class="glyphicon glyphicon-arrow-up"></span>
          <% end %>
        <% end %>
        <p class="text-center"><%= comment.up_votes.count - comment.down_votes.count %></p>
        <%= form_for current_user.down_votes.new(votable: comment) do |f| %>
          <%= f.hidden_field :votable_type %>
          <%= f.hidden_field :votable_id %>
          <%= f.button type: :submit, class: 'btn btn-default' do %>
            <span class="glyphicon glyphicon-arrow-down"></span>
          <% end %>
        <% end %>
      </div>

    </div>
    
    <div class="list-group">
      <%= render comment.comments %>
    </div>

  </div>
  
  <div class="panel-footer">
    <small>Posted by <em><%= comment.user.email %></em> on<%= time_ago_in_words comment.created_at %> 
      <span class="pull-right">
        <%= link_to 'Permalink', comment_url(comment), class: 'btn btn-default btn-xs' %> 
        <%= link_to 'Reply', '#reply', data: {toggle: 'collapse', target: "##{dom_id(comment)}-reply"}, class: 'btn btn-xs btn-info' %>
      </span> 
    </small>
  
    <div class="collapse" id="<%= dom_id(comment) %>-reply">
      <%= render 'comments/form', comment: current_user.comments.new(commentable: comment) %>
    </div>
  </div>

  <p><%= link_to 'Close thread', comment_close_thread_path(comment), method: :post, class: 'btn btn-default' %></p>
</div>

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :commentable_type %>
  <%= f.hidden_field :commentable_id %>

  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Commentable</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.commentable %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user.email %>
</p>

<p>
  <strong>Commentable:</strong>
  <%= @comment.commentable_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NerdNews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="nav navbar navbar-default">
    <div class="container">
      
      <%= link_to 'Nerd News', root_path, class: 'navbar-brand' %>
      
      <% if user_signed_in? %>
        <%= link_to 'New Post', new_post_path, class: 'btn btn-default navbar-btn' %>
      <% end %>

      <div class="navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">Signed in as <em><%= current_user.email %></em></p>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn btn-xs' %>
        <% else %>
          <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-default navbar-btn btn-xs' %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn btn-xs' %>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for post do |f| %>

  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :lock_version%>

  <fieldset class="form-group">
    <%= f.label :headline %>
    <%= f.text_field :headline, class: 'form-control' %>
  </fieldset>  

  <fieldset class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control' %>
  </fieldset>

  <%= f.submit 'Submit', class: 'btn btn-primary' %>

<% end %>

app/views/posts/conflict.html.erb
<h1>Fix Conflict</h1>

<p>Another user has updated this post and a conflict has occured. Please try again. You submitted the following updates:</p>

<dl>
  
  <dt>URL</dt>
  <dd><%= params[:post][:url] %></dd>

  <dt>Headline</dt>
  <dd><%= params[:post][:headline] %></dd>

</dl>

<%= render 'form', post: @post %>

app/views/posts/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Post#destroy</h1>
<p>Find me in app/views/post/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-12">

    <% @posts.each do |post| %>
      <div class="row">

        <div class="panel panel-default">
          <div class="panel-body">
            <h2><%= link_to post.headline, post_path(post) %></h2>
          </div>
          <div class="panel-footer">
            <small>Posted by <em><%= post.user.email %></em> on <%= time_ago_in_words post.created_at %> | <%= post.comments.count %> replies</small>
          </div>
        </div>
        
      </div>
    <% end %>
    
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="row">
  
  <div class="col-md-12">
  
    <div class="list-group-item">

      <div class="page-header">
        <h1><%= @post.headline %></h1>
        <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-default btn-xs pull-right' %>

        <%= form_for current_user.up_votes.new(votable: @post) do |f| %>
          <%= f.hidden_field :votable_type %>
          <%= f.hidden_field :votable_id %>
          <%= f.button type: :submit, class: 'btn btn-default' do %>
            <span class="glyphicon glyphicon-arrow-up"></span>
          <% end %>
        <% end %>
        <p class="text-center"><%= @post.up_votes.count - @post.down_votes.count %></p>
        <%= form_for current_user.down_votes.new(votable: @post) do |f| %>
          <%= f.hidden_field :votable_type %>
          <%= f.hidden_field :votable_id %>
          <%= f.button type: :submit, class: 'btn btn-default' do %>
            <span class="glyphicon glyphicon-arrow-down"></span>
          <% end %>
        <% end %>

        <small>Posted by <em><%= @post.user.email %></em> on <%= time_ago_in_words @post.created_at %></small>
      </div>

      <%= render 'comments/form', comment: current_user.comments.new(commentable:@post) %>

      <div class="list-group">
        <%= render @post.comments %>
      </div>

    </div>

  </div>
  
</div>

app/views/posts/update.html.erb
<h1>Post#update</h1>
<p>Find me in app/views/post/update.html.erb</p>